ingress:
  host: "argocd.yourdomain.com"
  issuer: "letsencrypt"
  className: "nginx"

argo-cd:
  redis:
    create: true

  controller:
    replicas: 1

  server:
    replicas: 2

  repoServer:
    replicas: 2

  applicationSet:
    replicaCount: 2
