apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-04-20T14:49:50Z"
  labels:
    app.kubernetes.io/created-by: tf-controller
    app.kubernetes.io/instance: tf-runner-dbc4ede1
    app.kubernetes.io/name: tf-runner
    infra.contrib.fluxcd.io/terraform: flux-system
    tf.weave.works/tls-secret-name: terraform-runner.tls-1713710973
  name: gitops-terraform-automation-tf-runner
  namespace: flux-system
  resourceVersion: "22441"
  uid: b2010fda-ea85-465e-b93b-df1c0dedad7e
spec:
  containers:
  - args:
    - --grpc-port
    - "30000"
    - --tls-secret-name
    - terraform-runner.tls-1713710973
    - --grpc-max-message-size
    - "30"
    env:
    - name: ARM_CLIENT_ID
      valueFrom:
        secretKeyRef:
          key: ARM_CLIENT_ID
          name: azure-creds
    - name: ARM_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          key: ARM_CLIENT_SECRET
          name: azure-creds
    - name: ARM_TENANT_ID
      valueFrom:
        secretKeyRef:
          key: ARM_TENANT_ID
          name: azure-creds
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: ARM_SUBSCRIPTION_ID
      valueFrom:
        secretKeyRef:
          key: ARM_SUBSCRIPTION_ID
          name: azure-creds
    image: mcr.microsoft.com/azure-cli
    imagePullPolicy: IfNotPresent
    name: tf-runner
    ports:
    - containerPort: 30000
      name: grpc
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 65532
      seccompProfile:
        type: RuntimeDefault
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tmp
      name: temp
    - mountPath: /home/runner
      name: home
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-6xcws
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: local-flux-cluster
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: tf-runner
  serviceAccountName: tf-runner
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: temp
  - emptyDir: {}
    name: home
  - name: kube-api-access-6xcws
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-04-20T14:49:52Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2024-04-20T14:49:50Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-04-20T14:49:50Z"
    message: 'containers with unready status: [tf-runner]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-04-20T14:49:50Z"
    message: 'containers with unready status: [tf-runner]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-04-20T14:49:50Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://8304f5f9eb98b020d2e9ad3e1a59e8581ef2127ed67ae9eb6d9d6c714caab916
    image: mcr.microsoft.com/azure-cli:latest
    imageID: docker-pullable://mcr.microsoft.com/azure-cli@sha256:eb21a975e39a46f49b86ab517ea2916e146560c7844d0c488cf85eee8a38398d
    lastState:
      terminated:
        containerID: docker://8304f5f9eb98b020d2e9ad3e1a59e8581ef2127ed67ae9eb6d9d6c714caab916
        exitCode: 127
        finishedAt: "2024-04-20T14:51:28Z"
        message: 'failed to create task for container: failed to create shim task:
          OCI runtime create failed: runc create failed: unable to start container
          process: exec: "--grpc-port": executable file not found in $PATH: unknown'
        reason: ContainerCannotRun
        startedAt: "2024-04-20T14:51:28Z"
    name: tf-runner
    ready: false
    restartCount: 4
    started: false
    state:
      waiting:
        message: back-off 1m20s restarting failed container=tf-runner pod=gitops-terraform-automation-tf-runner_flux-system(b2010fda-ea85-465e-b93b-df1c0dedad7e)
        reason: CrashLoopBackOff
  hostIP: 192.168.58.2
  hostIPs:
  - ip: 192.168.58.2
  phase: Running
  podIP: 10.244.0.25
  podIPs:
  - ip: 10.244.0.25
  qosClass: BestEffort
  startTime: "2024-04-20T14:49:50Z"
