opencost:
  opencost:
    customPricing:
      # -- Enables custom pricing for on-premise setup.
      enabled: true
      configmapName: custom-pricing-model
      # -- Path for the pricing configuration.
      configPath: /tmp/custom-config
      # -- Configures the pricing model provided in the values file.
      createConfigmap: true
      # -- More information about these values here: https://www.opencost.io/docs/configuration/on-prem#custom-pricing-using-the-opencost-helm-chart
      costModel:
        description: Modified prices based on your internal pricing
        CPU: 1.5
        spotCPU: 0.01023
        RAM: 0.75
        spotRAM: 0.00103
        GPU: 0.8
        storage: 0.3
        zoneNetworkEgress: 0.05
        regionNetworkEgress: 0.05
        internetNetworkEgress: 0.10
