apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            env: dev #cluster label
            core-basic: enabled
            security-basic: enabled
        values:
          branch: main #point to main branch
    - clusters:
        selector:
          matchLabels:
            env: prod #cluster label
            core-basic: enabled
            security-basic: enabled
        values:
          branch: main #point to main branch
  template:
    metadata:
      name: "{{name}}-cert-manager" #name of cluster + name of application
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: default
      sources:
        - repoURL: git@github.com:PacktPublishing/Implementing-GitOps-with-Kubernetes.git #custom values repo
          targetRevision: main #point to main branch of custom values repo
          ref: valuesRepo #use valuesRepo variable
        - repoURL: git@github.com:PacktPublishing/Implementing-GitOps-with-Kubernetes.git #umbrella repo
          targetRevision: "{{values.branch}}" #point to the branch depending on the cluster branch pointer
          path: "./chapter05/chapter-5-building-a-service-catalog-for-kubernetes/security/cert-manager" #path to the application in the umbrella repo
          helm:
            releaseName: "cert-manager" # Release name override (defaults to application name)
            valueFiles:
              - "values.yaml" #use values.yaml from umbrella repo
              - "$valuesRepo/chapter05/chapter-5-building-a-service-catalog-for-kubernetes/cluster/{{name}}/security/cert-manager/values.yaml" #override umbrella values from custom values repo
      destination:
        name: "{{name}}"
        namespace: "cert-manager"
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
