kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-admin
  namespace: vcluster-team-a
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: sso:DEV_Team_K8s_Dev@example.com
    apiGroup: rbac.authorization.k8s.io
