name: Publish Docker image

on:
  push:
    branches:
      - 'master'    # Trigger when changes are pushed to master branch
      - 'release'   # Trigger when changes are pushed to release branch
    paths:
      - 'module04/argocd_gitops/**'  # Only trigger if files in this directory are modified

  # Optionally allow manual trigger via the GitHub UI
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to trigger the build from'
        required: true
        default: 'master'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Check out the repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Cache Docker layers to speed up builds
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          cd module04/argocd_gitops  # Navigate to the directory containing the Dockerfile
          docker build -t module04 .  # Build the Docker image using Dockerfile in this folder

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username stored in GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password or token stored in GitHub Secrets

      # Step 6: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push module04  # Push the Docker image to Docker Hub
