apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: "ghcr.io/la-cc/simple-webapp:1.1.0-prod"
          name: simple-webapp
          env:
            - name: UI_X_COLOR
              value: premium
